# Generated by Django 5.2.17 on 2026-10-06 01:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operating_system', models.CharField(choices=[('windows', 'Windows'), ('ubuntu', 'Ubuntu'), ('linux', 'Linux')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('protocol', models.CharField(choices=[('rdp', 'RDP desktop'), ('vnc', 'VNC desktop'), ('ssh', 'SSH terminal')], default='rdp', max_length=3)),
                ('hostname', models.CharField(help_text='VM IP/DNS reachable FROM guacd, not the browser. No URL prefix.', max_length=253)),
                ('port', models.PositiveIntegerField(default=3389, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(blank=True, max_length=150)),
                ('domain', models.CharField(blank=True, help_text='RDP only; usually blank for local Windows accounts.', max_length=150)),
                ('password_encrypted', models.TextField(blank=True, editable=False)),
                ('ignore_certificate', models.BooleanField(default=False, help_text='RDP: enable only for your known lab VM with a self-signed certificate.')),
                ('rdp_security', models.CharField(choices=[('nla', 'NLA (Windows)'), ('tls', 'TLS (e.g. xrdp)'), ('any', 'Negotiate')], default='nla', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='assigned_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('django_session_key', models.CharField(max_length=40)),
                ('token_encrypted', models.TextField()),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('stop_requested', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
